server:
  build: .
  command: bin/server
  ports:
    - '8080:8080'
  volumes:
    - '$DOCKER_CERT_PATH:/home/.docker'
  environment:
    - DOCKER_CERT_PATH=/home/.docker
    - DOCKER_HOST
    - DOCKER_TLS_VERIFY
    - DOCKER_RUNNERS_URL
    - REPOSITORY
    - TEST_OPTS
    - NEW_RELIC_LICENSE_KEY
    - NEW_RELIC_APP_NAME
    - CODECLIMATE_REPO_TOKEN

ci:
  build: .
  command: bin/server
  environment:
    - DOCKER_RUNNERS_URL
    - CODECLIMATE_REPO_TOKEN
