server:
  build: .
  command: scripts/server.sh
  ports:
    - 8080:8080
  volumes:
    - $DOCKER_CERT_PATH:/home/.docker
  environment:
    - DOCKER_URL
    - DOCKER_RUNNERS_URL
    - REPOSITORY
    - TEST_OPTS
    - NEW_RELIC_LICENSE_KEY
    - NEW_RELIC_APP_NAME
